# Site settings
title: Jacqueline Li
description: My personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jacqueline Li
user_description: |- 
  Hi, my name is Jacqueline and I’m currently a computer science student at the University of Waterloo. I’m passionate about software development, learning new things, and bringing people together.

  At my previous engineering internships, I’ve helped develop 800+ microservices to automate accountant and book-keeper tasks using Javascript libraries. I’ve also created websites that have attracted over $50,000 in cancer research funding. Being able to make impact and ultimately help people is what drives my work. 
  
  I’m currently looking for SWE or PM internship opportunities for Fall/Winter 2020. 
  If you know of any cool opportunities or would like to chat, please shoot me a message!
user_title: Welcome to my website.
email: jacquelineli1005@gmail.com
#twitter_username: lorem_ipsum
github_username:  jacqueline-li
feedback_xero: |-
  "Jacqueline is a solid developer and unflaggingly positive. She demonstrates a strong interest in the work and a perseverance to solve difficult problems; even pulling other people's solutions to problems that stymied her to investigate how they were solved. 
  She maintained excellent communication when working on more complex fixes, asked thoughtful questions and provided insightful input during team OKRs. 
  
  Jacqueline, through asking thoughtful questions and acting as spokesperson for the team demonstrated the seeds of good communication and leadership skills. She was a pleasure to work with throughout the term."
feedback_oicr:  |-
  "Jacqueline has an excellent work ethic and continuously exceeded our expectations in the difficulty of the work she was able to successfully complete. She contributed to our most important projects and consistently completed her work ahead of schedule. 

  She also displayed enthusiasm for work that is beyond her job requirements, pro-actively seeking new tasks and responsibilities. Jacqueline would be a positive addition to any of her future endeavours. Thank you for all the great work, Jacqueline."

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
